import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

export const SDD_INSTALL_PATH = path.join(os.homedir(), ".local", "bin", "sdd");

export interface SddLauncherRender {
  source: string;
  shebang: string;
  body: string;
}

export function renderSddLauncher(
  boardDir: string,
  installedAt: Date = new Date(),
): string {
  const escapedDir = boardDir.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const date = installedAt.toISOString().slice(0, 10);

  const body = `// sdd — launcher for the sdd-sessions-board.
// Generated by openspec-board installer on ${date}.
// Override the board directory via SDD_BOARD_DIR=<path> in your shell.

const SDD_BOARD_DIR = process.env.SDD_BOARD_DIR || "${escapedDir}";

const args = process.argv.slice(2);

if (args.includes("--help") || args.includes("-h")) {
  process.stdout.write(
    [
      "sdd — launcher for the sdd-sessions-board",
      "",
      "Usage: sdd [options]",
      "",
      "Options:",
      "  --where    Print the configured board directory and exit.",
      "  --help     Show this help and exit.",
      "",
      "Environment:",
      "  SDD_BOARD_DIR    Override the board directory.",
      "",
      "Configured board: " + SDD_BOARD_DIR,
      "",
    ].join("\\n"),
  );
  process.exit(0);
}

if (args.includes("--where")) {
  process.stdout.write(SDD_BOARD_DIR + "\\n");
  process.exit(0);
}

const fs = require("node:fs");
if (!fs.existsSync(SDD_BOARD_DIR)) {
  process.stderr.write(
    "sdd: директория доски не найдена: " + SDD_BOARD_DIR + "\\n" +
    "    Переустановите доску или задайте SDD_BOARD_DIR=<path> в окружении.\\n",
  );
  process.exit(1);
}

const { spawn } = require("node:child_process");

const proc = spawn("npm", ["run", "dev"], {
  cwd: SDD_BOARD_DIR,
  stdio: "inherit",
  env: process.env,
});

for (const signal of ["SIGINT", "SIGTERM", "SIGHUP"]) {
  process.on(signal, () => {
    if (!proc.killed) {
      try {
        proc.kill(signal);
      } catch (_error) {
        // best-effort forwarding
      }
    }
  });
}

proc.on("exit", (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
  } else {
    process.exit(code ?? 0);
  }
});
`;

  return `#!/usr/bin/env node\n${body}`;
}

export function installSddLauncher(
  boardDir: string,
  targetPath: string = SDD_INSTALL_PATH,
): { path: string; onPath: boolean } {
  const targetDir = path.dirname(targetPath);
  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }
  const source = renderSddLauncher(boardDir);
  writeFileSync(targetPath, source, { encoding: "utf8", mode: 0o755 });
  chmodSync(targetPath, 0o755);
  return {
    path: targetPath,
    onPath: isOnPath(targetDir),
  };
}

export function isOnPath(binDir: string): boolean {
  const sep = process.platform === "win32" ? ";" : ":";
  const pathDirs = (process.env.PATH ?? "").split(sep);
  return pathDirs.some((p) => path.resolve(p) === path.resolve(binDir));
}