/**
 * Helpers for deleting OpenSpec change-folder artefacts that were
 * generated by the auto pipeline. Used by the "Редактировать"
 * action: when the analyst reverts a done task back to an earlier
 * stage with a comment, the artefacts produced by the later
 * stages become stale and need to be removed so the gigacode
 * re-write starts from a clean slate.
 *
 * Scope: the change folder <worktree>/openspec/changes/<tag>/.
 * The worktree itself, the branch, and the parent state.json are
 * left untouched — those are managed by other helpers.
 */

import path from "path";
import fs from "fs/promises";

import type { Stage } from "./openspec";

/**
 * Map of each "revert-target" stage to the set of artefacts to
 * delete because they were produced by a later stage. The sets
 * are inclusive of the target stage itself so that "revert to
 * proposal" wipes everything that was generated after the
 * proposal, including the proposal.md file itself.
 */
const ARTEFACTS_TO_DELETE: Record<Stage, string[]> = {
  proposal: [
    "proposal.md",
    "design.md",
    "adr.md",
  ],
  "delta-spec": [
    "specs",
    "design.md",
    "adr.md",
  ],
  design: [
    "design.md",
    "adr.md",
  ],
  adr: [
    "adr.md",
  ],
  // developer-mode stages — not used by the analyst "Редактировать"
  // flow, but kept here so the helper stays total.
  backlog: [],
  decomposition: [],
  plan: [],
  develop: [],
  tests: [],
  deploy: [],
  done: [],
};

/**
 * Remove the artefacts produced by every stage strictly *after*
 * `targetStage` in the OpenSpec change-folder under
 * <worktree>/openspec/changes/<tag>/. Per the table above, the
 * target's own artefact is also removed — "revert to proposal"
 * means "start the proposal generation from scratch", which
 * requires wiping the previous proposal.md.
 *
 * Returns the list of paths that were actually removed (so the
 * caller can show them in the toast / log).
 */
export async function deleteArtefactsAfterStage(
  worktree: string,
  changeName: string,
  targetStage: Stage,
): Promise<string[]> {
  const changePath = path.join(worktree, "openspec", "changes", changeName);
  const toDelete = ARTEFACTS_TO_DELETE[targetStage] ?? [];
  const removed: string[] = [];

  for (const rel of toDelete) {
    const abs = path.join(changePath, rel);
    try {
      const stat = await fs.lstat(abs);
      if (stat.isDirectory()) {
        await fs.rm(abs, { recursive: true, force: true });
      } else {
        await fs.unlink(abs);
      }
      removed.push(abs);
    } catch (e) {
      const err = e as NodeJS.ErrnoException;
      if (err.code !== "ENOENT") {
        // Surface but don't fail the whole revert — best-effort.
        console.warn(
          `Failed to remove ${abs} while reverting ${changeName}:`,
          e,
        );
      }
    }
  }
  return removed;
}