import type { Session, Stage, StageMeta } from "./types";

export const sessions: Session[] = [
  {
    id: "OS-001",
    title: "Add user authentication via OAuth2",
    changeName: "add-oauth2-auth",
    stage: "backlog",
    priority: "high",
    labels: [
      { name: "auth", color: "#3b82f6" },
      { name: "security", color: "#ef4444" },
    ],
    assignee: { name: "Anna K.", initials: "AK", color: "#fbbf24" },
    createdAt: "2026-07-14T09:00:00Z",
    comments: 3,
    tasksProgress: { done: 0, total: 5 },
  },
  {
    id: "OS-002",
    title: "Migrate legacy session storage to Redis",
    changeName: "redis-session-storage",
    stage: "backlog",
    priority: "medium",
    labels: [{ name: "infra", color: "#8b5cf6" }],
    assignee: { name: "Max D.", initials: "MD", color: "#34d399" },
    createdAt: "2026-07-15T11:30:00Z",
    comments: 1,
    tasksProgress: { done: 0, total: 4 },
  },
  {
    id: "OS-003",
    title: "Decompose billing domain into bounded contexts",
    changeName: "decompose-billing-domain",
    stage: "decomposition",
    priority: "high",
    labels: [
      { name: "domain", color: "#06b6d4" },
      { name: "refactor", color: "#f59e0b" },
    ],
    assignee: { name: "Olga R.", initials: "OR", color: "#a78bfa" },
    createdAt: "2026-07-12T08:15:00Z",
    comments: 5,
    tasksProgress: { done: 1, total: 6 },
  },
  {
    id: "OS-004",
    title: "Define event-sourced ledger contract",
    changeName: "design-event-ledger",
    stage: "plan",
    priority: "medium",
    labels: [
      { name: "design", color: "#8b5cf6" },
      { name: "events", color: "#10b981" },
    ],
    assignee: { name: "Igor S.", initials: "IS", color: "#f472b6" },
    createdAt: "2026-07-13T14:00:00Z",
    comments: 2,
    tasksProgress: { done: 2, total: 5 },
  },
  {
    id: "OS-005",
    title: "Implement idempotency keys for /payments",
    changeName: "add-idempotency-keys",
    stage: "develop",
    priority: "high",
    labels: [
      { name: "api", color: "#3b82f6" },
      { name: "reliability", color: "#10b981" },
    ],
    assignee: { name: "Pavel V.", initials: "PV", color: "#60a5fa" },
    createdAt: "2026-07-10T10:00:00Z",
    comments: 7,
    tasksProgress: { done: 3, total: 5 },
  },
  {
    id: "OS-006",
    title: "Wire Stripe webhooks into retry policy",
    changeName: "stripe-webhook-retries",
    stage: "develop",
    priority: "medium",
    labels: [
      { name: "integration", color: "#06b6d4" },
      { name: "stripe", color: "#635bff" },
    ],
    assignee: { name: "Nina T.", initials: "NT", color: "#fb923c" },
    createdAt: "2026-07-11T12:45:00Z",
    comments: 4,
    tasksProgress: { done: 2, total: 6 },
  },
  {
    id: "OS-007",
    title: "Add contract tests for /invoices endpoint",
    changeName: "invoices-contract-tests",
    stage: "tests",
    priority: "urgent",
    labels: [
      { name: "tests", color: "#06b6d4" },
      { name: "contract", color: "#22c55e" },
    ],
    assignee: { name: "Anna K.", initials: "AK", color: "#fbbf24" },
    createdAt: "2026-07-09T08:30:00Z",
    comments: 6,
    tasksProgress: { done: 4, total: 5 },
  },
  {
    id: "OS-008",
    title: "Roll out k8s canary 10%",
    changeName: "k8s-canary-rollout",
    stage: "deploy",
    priority: "high",
    labels: [
      { name: "infra", color: "#8b5cf6" },
      { name: "k8s", color: "#326ce5" },
    ],
    assignee: { name: "Max D.", initials: "MD", color: "#34d399" },
    createdAt: "2026-07-08T16:00:00Z",
    comments: 9,
    tasksProgress: { done: 4, total: 5 },
  },
  {
    id: "OS-009",
    title: "Add structured logging to auth service",
    changeName: "add-structured-logging",
    stage: "done",
    priority: "low",
    labels: [{ name: "observability", color: "#22c55e" }],
    assignee: { name: "Olga R.", initials: "OR", color: "#a78bfa" },
    createdAt: "2026-07-01T09:00:00Z",
    comments: 2,
    tasksProgress: { done: 4, total: 4 },
  },
  {
    id: "OS-010",
    title: "Refactor JPA entities to Kotlin value classes",
    changeName: "refactor-jpa-entities",
    stage: "done",
    priority: "medium",
    labels: [
      { name: "refactor", color: "#f59e0b" },
      { name: "kotlin", color: "#a78bfa" },
    ],
    assignee: { name: "Igor S.", initials: "IS", color: "#f472b6" },
    createdAt: "2026-06-28T13:20:00Z",
    comments: 3,
    tasksProgress: { done: 5, total: 5 },
  },
];

export const STAGES_ORDER: Stage[] = [
  "backlog",
  "decomposition",
  "plan",
  "develop",
  "tests",
  "deploy",
  "done",
];

export const STAGE_META: Record<Stage, StageMeta> = {
  backlog: { label: "Бэклог", icon: "Inbox" },
  decomposition: { label: "Декомпозиция", icon: "GitBranch" },
  plan: { label: "План", icon: "ClipboardList" },
  develop: { label: "Разработка", icon: "Code2" },
  tests: { label: "Тесты", icon: "TestTube2" },
  deploy: { label: "Деплой", icon: "Rocket" },
  done: { label: "Готово", icon: "CheckCircle2" },
};